apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acm-data
  namespace: acm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
